### ISSUE TITLE
Name for this project

### ISSUE THREAD

**Issue by amaury1093** [chronoscio/frontend#2]
As pointed out by @whirish, "Interactive Map" isn't really catchy nor explicit. We should probably think of a better name for our project.

**Comment by amaury1093** [comment]
Some ideas:

- Wikihistory
- Humanity (very difficult to make domain name, SEO etc work, maybe a variant of it?)

**Comment by quorth0n** [comment]
We could also consider including the word 'Open' in the name.

**Comment by bapo224** [comment]
Maybe a merge word (like HumaniMap etc) or Latin (orbis terrarum historiae or fabulis terrarum etc)

**Comment by amaury1093** [comment]
I like the latin idea. I would go for a short name, maybe historia only, but then it's also Spanish.

**Comment by jpeppelman** [comment]
I also have some ideas:

- I would like to see “Historical Atlas” included in the name: Open Historical Atlas, osm Historical Atlas or Online Historical Atlas. 
I prefer the term Atlas over the term Map. Because our project includes multiple maps instead of one and we also provide information on the states in the maps.

- Another name I like is “Ortelius”. It’s the Latinized name of Abraham Ortels. Ortelius was a famous 16th century geographer who made the Theatrum Orbis Terrarum. He also made the first historical atlas.
We could consider adding an explicit subtitle: open historical atlas (or something similar)

**Comment by bapo224** [comment]
I like the idea of having 'Open Historical Atlas' as our subtitle. So like: '[CHOSEN NAME]: An open historical atlas' or something like that. But it shouldn't be our primary project name since it's not really unique/catchy.

**Comment by jpeppelman** [comment]
@bapo224 That's a fair point, I agree

**Comment by quorth0n** [comment]
+1 for Atlas over map, though I do think Open or Wiki should be in the primary name. A more descriptive subtitle is definitely a solid idea

**Comment by Improvised-username** [comment]
i think "atlas" should be in the name but unfortunately "atlas" means a BOOK of maps or charts

**Comment by jpeppelman** [comment]
The definition of an atlas is a collection of maps. This can either be in a book or  digital. Here is an example of a digital atlas of the Roman Empire: http://dare.ht.lu.se/

**Comment by quorth0n** [comment]
I like the names OpenAtlas or WikiAtlas personally

**Comment by quorth0n** [comment]
ἀνοίγω and aperta are 'open' in Greek (Atlas is a Greek word) and Latin respectively, we could consider using one of these terms in the title.

**Comment by amaury1093** [comment]
Following @jpeppelman's idea on famous historians/geographers, I can propose:
- Pausanias
- Strabo
- Pytheas

**Comment by amaury1093** [comment]
One thing to keep in mind too is Google search results. For example, OpenAtlas already exists, and it'd not be wise imo to compete with them on the same name.

**Comment by bapo224** [comment]
popularity poll:
[see Slack]

**Comment by bapo224** [comment]
OpenAtlas, WikiAtlas, WikiHistory, Historia, Strabo, Pytheas and Ortelius are also already in use btw

**Comment by quorth0n** [comment]
Slack poll concluded with `ChronoScio` as our name for the foreseeable future.
