### ISSUE TITLE
Create an `api` package to handle backend responses

### ISSUE THREAD

**Issue by amaury1093** [chronoscio/frontend#21]
Create a `@chronoscio/api` package, where we:
- manage the axios requests in one place
- create TS interfaces for all our models
- add validations for these models

So that basically we have:
`backend ---send json--->@chronoscio/api, who processes and normalizes data ---sends normalized, typed data ---> rest of app`

cc @whirish let's do this after we merge your PR.

**Comment by quorth0n** [comment]
Closed via #24
